# SIMPLE NEURAL NETWORKS FROM SCRATCH

In [1]:
# Import required libraries
import numpy as np

In [2]:
# Define input features:
input_features = np.array([[0,0], [0,1], [1,0], [1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
# Define target output:
target_output = np.array([[0,1,1,1]])

# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)

print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [12]:
# Define weghts:

# 6 to hidden, 3 to output layer
weight_hidden = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
weight_output = np.array([[0.7], [0.8], [0.9]])

# learning rate
lr = 0.05

In [6]:
# Bias weight:
bias = 0.3



In [5]:
# Sigmoid function:
def sigmoid(X):
  val = 1/(1+np.exp(-X))
  return val

In [6]:
# Derivative of sigmoid function
def sigmoid_der(X):
    return sigmoid(X)*(1-sigmoid(X))

In [14]:
for epoch in range(200000):
 # Input for hidden layer :
 input_hidden = np.dot(input_features, weight_hidden)
 
 # Output from hidden layer :
 output_hidden = sigmoid(input_hidden)
 
 # Input for output layer :
 input_op = np.dot(output_hidden, weight_output)
 
 # Output from output layer :
 output_op = sigmoid(input_op)
 
 #==========================================================
 # Phase1
 
 # Calculating Mean Squared Error :
 error_out = ((1 / 2) * (np.power((output_op - target_output), 2)))
 print(error_out.sum())
 
 # Derivatives for phase 1 :
 derror_douto = output_op - target_output
 douto_dino = sigmoid_der(input_op) 
 dino_dwo = output_hidden
 
 derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)
 
 #===========================================================
 # Phase 2 
 # derror_w1 = derror_douth * douth_dinh * dinh_dw1
 # derror_douth = derror_dino * dino_outh
 
 # Derivatives for phase 2 :
 derror_dino = derror_douto * douto_dino
 dino_douth = weight_output
 derror_douth = np.dot(derror_dino , dino_douth.T)
 douth_dinh = sigmoid_der(input_hidden) 
 dinh_dwh = input_features
 derror_wh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)
 
 # Update Weights
 weight_hidden -= lr * derror_wh
 weight_output -= lr * derror_dwo
 

297
0.00026627387986488015
0.0002662724613089033
0.0002662710427678956
0.00026626962424185967
0.0002662682057307928
0.000266266787234699
0.0002662653687535751
0.0002662639502874193
0.00026626253183623534
0.00026626111340002223
0.00026625969497877665
0.00026625827657249734
0.00026625685818118967
0.00026625543980484946
0.00026625402144347926
0.0002662526030970772
0.00026625118476564274
0.00026624976644917434
0.00026624834814767173
0.0002662469298611405
0.000266245511589575
0.00026624409333297536
0.00026624267509134185
0.00026624125686467543
0.00026623983865297507
0.0002662384204562399
0.0002662370022744689
0.0002662355841076663
0.0002662341659558264
0.0002662327478189531
0.00026623132969704236
0.00026622991159009826
0.00026622849349811664
0.0002662270754210995
0.00026622565735904484
0.0002662242393119548
0.00026622282127982853
0.00026622140326266433
0.00026621998526046034
0.00026621856727322045
0.0002662171493009441
0.000266215731343629
0.0002662143134012767
0.0002662128954738836
0.00026

In [15]:
# Final hidden layer weight values :
print (weight_hidden)

# Final output layer weight values :
print (weight_output)

[[-3.82270773  2.36324803  3.13867107]
 [-3.79490945  2.45183148  3.18541383]]
[[-13.22689481]
 [  1.74391783]
 [  3.50426502]]


In [16]:
# Predictions :
# Taking inputs :
single_point = np.array([0,1])

# 1st step :
result1 = np.dot(single_point, weight_hidden) 

# 2nd step :
result2 = sigmoid(result1)

# 3rd step :
result3 = np.dot(result2,weight_output)

# 4th step :
result4 = sigmoid(result3)
print(result4)

[0.99462917]
