# SIMPLE NEURAL NETWORKS FROM SCRATCH

In [2]:
# Import required libraries
import numpy as np

In [3]:
# Define input features:
input_features = np.array([[0,0], [0,1], [1,0], [1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
# Define target output:
target_output = np.array([[0,1,1,1]])

# Reshaping our target output into vector:
target_output = target_output.reshape(4,1)

print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [5]:
# Define weghts:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [6]:
# Bias weight:
bias = 0.3

# learning rate
lr = 0.05

In [7]:
# Sigmoid function:
def sigmoid(X):
  val = 1/(1+np.exp(-X))
  return val

In [8]:
# Derivative of sigmoid function
def sigmoid_der(X):
    return sigmoid(X)*(1-sigmoid(X))

In [9]:
# Main logic for neural network:
# Running our code 10000 times:
for epoch in range(10000):
    inputs = input_features
    
    # Feedforward input:
    in_o = np.dot(inputs, weights) + bias 
    
    # Feedforward output:
    out_o = sigmoid(in_o) 
    
    # Backpropogation
    # Calculating error
    error = out_o - target_output
    
    # Going with the formula:
    x = error.sum()
    print(x)
    
    # Calculating derivative:
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives:
    deriv = derror_douto * douto_dino 
    
    # Multiplying with the 3rd individual derivative:
    # Finding the transpose of input_features:
    inputs = input_features.T
    deriv_final = np.dot(inputs,deriv)

    # Updating the weights values:
    weights -= lr * deriv_final 
    
    # Updating the bias weight value:
    for i in deriv:
        bias -= lr * i 

215894915704e-05
-9.784829247203725e-05
-9.791439437918659e-05
-9.79804646864188e-05
-9.804650340955456e-05
-9.81125105645464e-05
-9.817848616728436e-05
-9.824443023379037e-05
-9.831034278046102e-05
-9.837622382213862e-05
-9.844207337586508e-05
-9.850789145656597e-05
-9.857367808060319e-05
-9.863943326430397e-05
-9.870515702253141e-05
-9.877084937173763e-05
-9.883651032795149e-05
-9.890213990662589e-05
-9.896773812381049e-05
-9.903330499519414e-05
-9.909884053656975e-05
-9.916434476404945e-05
-9.922981769264899e-05
-9.929525933911887e-05
-9.936066971907159e-05
-9.942604884761314e-05
-9.949139674107765e-05
-9.955671341475153e-05
-9.962199888502443e-05
-9.96872531670856e-05
-9.975247627706796e-05
-9.981766823013993e-05
-9.988282904239976e-05
-9.994795872950157e-05
-0.00010001305730714116
-0.00010007812479093797
-0.00010014316119605349
-0.00010020816653907166
-0.00010027314083525113
-0.00010033808409996847
-0.00010040299634919009
-0.00010046787759847992
-0.00010053272786308964
-0.00010059

In [10]:
# Check the final values for weight and bias
print(weights)
print(bias)

[[7.00922425]
 [7.00953281]]
[-3.14905135]


In [11]:
#Taking inputs:
single_point = np.array([1,0]) 

# 1st step:
result1 = np.dot(single_point, weights) + bias 

# 2nd step:
result2 = sigmoid(result1) 

# Print final result
print(result2)

[0.9793702]


In [12]:
#Taking inputs:
single_point = np.array([1,1]) 

# 1st step:
result1 = np.dot(single_point, weights) + bias 

# 2nd step:
result2 = sigmoid(result1) 

# Print final result
print(result2)

[0.99998097]


In [13]:
#Taking inputs:
single_point = np.array([0,0]) 

# 1st step:
result1 = np.dot(single_point, weights) + bias 

# 2nd step:
result2 = sigmoid(result1) 

# Print final result
print(result2)

[0.04112867]
