# SIMPLE NEURAL NETWORKS: Predicting Virus Contraction

In [2]:
# Import required libraries :
import numpy as np

In [3]:
# Define input features :
input_features = np.array([[1,0,0,1],[1,0,0,0],[0,0,1,1],
                            [0,1,0,0],[1,1,0,0],[0,0,1,1],
                            [0,0,0,1],[0,0,1,0]])
                            
print (input_features.shape)
print (input_features)

(8, 4)
[[1 0 0 1]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 1 0]]


In [4]:
# Define target output :
target_output = np.array([[1,1,0,0,1,1,0,0]])

# Reshaping our target output into vector :
target_output = target_output.reshape(8,1)
print(target_output.shape)
print (target_output)

(8, 1)
[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]]


In [5]:
# Define weights :
weights = np.array([[0.1],[0.2],[0.3],[0.4]])
print(weights.shape)
print (weights)

(4, 1)
[[0.1]
 [0.2]
 [0.3]
 [0.4]]


In [9]:
# Bias weight :
bias = 0.3

# Learning Rate :
lr = 0.05

In [10]:
# Sigmoid function :
def sigmoid(x):
 return 1/(1+np.exp(-x))

In [11]:
# Derivative of sigmoid function :
def sigmoid_der(x):
 return sigmoid(x)*(1-sigmoid(x))

In [12]:
# Main logic for neural network :
# Running our code 10000 times :
for epoch in range(10000):
 inputs = input_features
 
 # Feedforward input :
 pred_in = np.dot(inputs, weights) + bias
 
 # Feedforward output :
 pred_out = sigmoid(pred_in)
 
 # Backpropogation 
 # Calculating error
 error = pred_out - target_output
 
 # Going with the formula :
 x = error.sum()
 print(x)
 
 # Calculating derivative :
 dcost_dpred = error
 dpred_dz = sigmoid_der(pred_out)
 
 # Multiplying individual derivatives :
 z_delta = dcost_dpred * dpred_dz
 
 # Multiplying with the 3rd individual derivative :
 inputs = input_features.T
 weights -= lr * np.dot(inputs, z_delta)
 
 # Updating the bias weight value :
 for i in z_delta:
  bias -= lr * i

00878042134160184
0.008779304981670455
0.008778188883562688
0.00877707304719344
0.008775957472474227
0.008774842159317231
0.008773727107637297
0.008772612317345996
0.008771497788356786
0.00877038352058146
0.008769269513934141
0.008768155768327235
0.008767042283675142
0.008765929059889377
0.008764816096884176
0.00876370339457172
0.008762590952864968
0.008761478771677822
0.008760366850923629
0.008759255190515736
0.008758143790368156
0.008757032650393404
0.008755921770505937
0.008754811150617436
0.008753700790643915
0.008752590690495776
0.008751480850090032
0.008750371269337698
0.00874926194815323
0.008748152886451033
0.008747044084144007
0.008745935541146277
0.00874482725737169
0.008743719232733427
0.00874261146714611
0.008741503960522978
0.008740396712779708
0.008739289723828425
0.008738182993583588
0.008737076521957932
0.008735970308867635
0.008734864354226657
0.008733758657949842
0.008732653219949482
0.008731548040139703
0.008730443118437015
0.008729338454753821
0.008728234049005246
0

In [13]:
#Printing final weights: 
print (weights)

print (bias)

[[10.1634992 ]
 [ 0.45744949]
 [ 2.97441782]
 [ 2.9938138 ]]
[-6.07764153]


In [15]:
# Taking inputs :
single_point = np.array([1,0,0,1])

# 1st step :
result1 = np.dot(single_point, weights) + bias

# 2nd step :
result2 = sigmoid(result1)

# Print final result
print(result2)

[0.99915866]


In [16]:
# Taking inputs :
single_point = np.array([0,0,1,0])

# 1st step :
result1 = np.dot(single_point, weights) + bias

# 2nd step :
result2 = sigmoid(result1)

# Print final result
print(result2)

[0.04297448]


In [ ]:
#Taking inputs :
single_point = np.array([1,0,1,0])

# 1st step :
result1 = np.dot(single_point, weights) + bias

# 2nd step :
result2 = sigmoid(result1)

# Print final result
print(result2)